### ISSUE TITLE
Addition of Background Color to the Margin Cells

### ISSUE THREAD

**Issue by akarshghildyal** [SukhOberoi/SRM-Margin-Check#4]
> To make content in the Margin cells uniform with the other cells, 

# Without Background Color
![image](https://github.com/SukhOberoi/SRM-Margin-Check/assets/129004417/d45186b0-3f25-4b21-9925-4c219bac49d4)

# With Background Color
![image](https://github.com/SukhOberoi/SRM-Margin-Check/assets/129004417/f2dcdeff-7f73-44b9-913a-ba2b78c344b8)

**Comment by akarshghildyal** [comment]
@SukhOberoi can you assign this to me ?

**Comment by SukhOberoi** [comment]
> @SukhOberoi can you assign this to me ?

Sure

**Comment by SukhOberoi** [comment]
Ill push the update tomorrow to the web store. thanks @akarshghildyal
